### ISSUE TITLE
Using `Transform` instead of `Writable`

### ISSUE THREAD

**Issue by jamen** [audiojs/out#4]
An idea I just had.

We were originally going to use `Writable`, but there is a few beefs I have with that:
1. Not really used that often standalone. (You usually use `Duplex` streams, which extend off it)
2. It breaks the pipeline, you can't do `.pipe(out()).pipe(...)`.
3. It doesn't allows us to easily measure the audio duration.

The main part of this issue is to "easily measure the audio duration"... 

Imagine you had a 7 second audio file, the stream could be delayed 7 seconds via an option:

``` javascript
// get `Audio` source somehow...
.pipe(out({ delay: true })) // delays stream for 7 seconds
.on('end', function() {
  console.log('Done playing');
});
```

Also would work in pipelines, i.e. playing mutlple sets of audio (instead of them playing over top of each other):

``` javascript
var output = out({ delay: true });

createAudio({ seconds: 5 })
.pipe(output) // delays for 5 seconds
.pipe(createAudio({ seconds: 3 }))
.pipe(output) // delays for 3 seconds
.on('end', function() {
  console.log('Played audio serially');
});
```

This could be accomplished easily with `Transform`, doing something like:

``` javascript
// Duration of the audio in milliseconds.
var duration = audio.length / audio._blockRate * 1000;

// Delaying the stream.
setTimeout(function() {
  callback(null, audio);
}, duration);
```

I do think it is important to have this as an option (whether or not enabled by default is up to you) because playing multiple pieces of audio at the same time (without delay) is important too.

Thoughts?

**Comment by vectrixdevelops** [comment]
This is quite good. Although I would assume the client would manage such things, this would be a nice feature to have native.
